### ISSUE TITLE
Data issues

### ISSUE THREAD

**Issue by happy20200** [plutoyuxie/Reconstruction-by-inpainting-for-visual-anomaly-detection#3]
![image](https://user-images.githubusercontent.com/59427046/110129593-15c27800-7e03-11eb-9159-4ab260046d59.png)
Hello， when I train with my own dataset, there is no problem, but when I test it, the following problem appears, what can I do to correct it， thank youuuuu～

**Comment by RohDonghyeon** [comment]
I also have the same problem.

How did you solve it?

**Comment by plutoyuxie** [comment]
@happy20200 @RohDonghyeon 

https://github.com/plutoyuxie/Reconstruction-by-inpainting-for-visual-anomaly-detection/issues/5
