### ISSUE TITLE
About custom data.

### ISSUE THREAD

**Issue by RohDonghyeon** [plutoyuxie/Reconstruction-by-inpainting-for-visual-anomaly-detection#4]
Thank you for providing a really interesting code.

Train, test, ground_truth were all resized to 500X500 and inserted into each directory.
However, the error below appears.

RuntimeError: stack expects each tensor to be equal size, but got [1, 256, 256] at entry 0 and [3, 256, 256] at entry 1

Can you tell me what the problem is?

**Comment by plutoyuxie** [comment]
Maybe some gray images and color images are blended, leading to tensor dimensions mismatch.

**Comment by RohDonghyeon** [comment]
I also figured out that the cause was the part the author explained.

However, as a result of checking, all images were the same size.

Above all, training works with the same data, but only testing causes the same problem.

Are there any other possible causes?

**Comment by RohDonghyeon** [comment]
The above question was solved by changing the batch size to 1. I'm guessing it's probably not a memory related issue.

But another problem occurred.
In the process of evaluation, 4 good data of bottle and 5 of broken_small data were put in and evlauated.

![1 (1)](https://user-images.githubusercontent.com/33896710/124219117-9cc7f880-db36-11eb-94f4-41ec8ac3fc6a.png)

As shown in the picture above, GT comes out well with 9.
But the score is 2304.
2304/256 = 9.
Therefor, the problem seems to be caused by not picking a score representing one image after picking the score of 256 pixels from one image.

Therefore, the process mentioned above seems to be missing in the code.
How do you make 256 scores of one image into scores of one image?
